version: '3.8'
services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./scripts:/scripts
    container_name: nginx-proxy
    restart: unless-stopped