version: '3.8'
services:
  crop-recommendation-blue:
    build: .
    ports:
      - "5002:5000"
    environment:
      - ENVIRONMENT=blue
      - VERSION=blue-${BUILD_NUMBER:-latest}
    container_name: crop-recommendation-blue
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s